/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.CollectionDAO;
import dao.ComicCollectionDAO;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Collection;
import model.Comic;

/**
 *
 * @author Mayara Medeiros
 */
public class TelaAddCollection extends javax.swing.JFrame {

    TelaCollections collections = new TelaCollections();
    TelaLogin login = new TelaLogin();
    TelaComics comics = new TelaComics();

    /**
     * Creates new form TelaAddCollection
     */
    public TelaAddCollection() {
        initComponents();
        preencherEspaços();
    }

    public void preencherEspaços(){
       
        try {
       
            titulojTextField.setText("");
            editorajTextField.setText("");
            numTotaljTextField.setText("");
            numAtualjTextField.setText("");
            
        } catch(Exception ex){
            System.err.println("ERRO GERAL..." + ex.getMessage());
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sycjLabel = new javax.swing.JLabel();
        superHeroisFundo = new javax.swing.JLabel();
        comicsjButton = new javax.swing.JButton();
        collectionsjButton = new javax.swing.JButton();
        emprestimosjButton = new javax.swing.JButton();
        dadosUserjButton = new javax.swing.JButton();
        nomeCollectionjLabel = new javax.swing.JLabel();
        titulojTextField = new javax.swing.JTextField();
        editorajTextField = new javax.swing.JTextField();
        editorajLabel = new javax.swing.JLabel();
        cancelarjButton = new javax.swing.JButton();
        salvarjButton = new javax.swing.JButton();
        numAtualjTextField = new javax.swing.JTextField();
        numTotaljTextField = new javax.swing.JTextField();
        titulojLabel = new javax.swing.JLabel();
        numTotaljLabel = new javax.swing.JLabel();
        numAtualjLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setLocation(new java.awt.Point(300, 100));
        setResizable(false);

        sycjLabel.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        sycjLabel.setForeground(new java.awt.Color(255, 255, 255));
        sycjLabel.setText("SeeYoursComics");
        sycjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sycjLabelMouseClicked(evt);
            }
        });

        superHeroisFundo.setBackground(new java.awt.Color(0, 0, 0));
        superHeroisFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/top-10-melhores-super-herois-noticias-the-history-channel (1).jpg"))); // NOI18N

        comicsjButton.setBackground(new java.awt.Color(255, 255, 255));
        comicsjButton.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        comicsjButton.setText("Comics");
        comicsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comicsjButtonActionPerformed(evt);
            }
        });

        collectionsjButton.setBackground(new java.awt.Color(255, 255, 255));
        collectionsjButton.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        collectionsjButton.setText("Collections");
        collectionsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectionsjButtonActionPerformed(evt);
            }
        });

        emprestimosjButton.setBackground(new java.awt.Color(255, 255, 255));
        emprestimosjButton.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        emprestimosjButton.setText("Loans");
        emprestimosjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprestimosjButtonActionPerformed(evt);
            }
        });

        dadosUserjButton.setBackground(new java.awt.Color(255, 255, 255));
        dadosUserjButton.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        dadosUserjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user.png"))); // NOI18N
        dadosUserjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dadosUserjButtonActionPerformed(evt);
            }
        });

        nomeCollectionjLabel.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        nomeCollectionjLabel.setForeground(new java.awt.Color(255, 255, 255));
        nomeCollectionjLabel.setText("New Collection");

        editorajTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editorajTextFieldActionPerformed(evt);
            }
        });

        editorajLabel.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        editorajLabel.setForeground(new java.awt.Color(255, 255, 255));
        editorajLabel.setText("Publishing Company");

        cancelarjButton.setBackground(new java.awt.Color(255, 255, 255));
        cancelarjButton.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        cancelarjButton.setText("Cancel");
        cancelarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarjButtonActionPerformed(evt);
            }
        });

        salvarjButton.setBackground(new java.awt.Color(255, 255, 255));
        salvarjButton.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        salvarjButton.setText("Save");
        salvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButtonActionPerformed(evt);
            }
        });

        titulojLabel.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        titulojLabel.setForeground(new java.awt.Color(255, 255, 255));
        titulojLabel.setText("Title");

        numTotaljLabel.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        numTotaljLabel.setForeground(new java.awt.Color(255, 255, 255));
        numTotaljLabel.setText(" Total");

        numAtualjLabel.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        numAtualjLabel.setForeground(new java.awt.Color(255, 255, 255));
        numAtualjLabel.setText("Current");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salvarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editorajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editorajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titulojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numAtualjTextField)
                            .addComponent(numTotaljTextField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(numAtualjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 20, Short.MAX_VALUE)))))
                .addGap(319, 319, 319))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(sycjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comicsjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(collectionsjButton)
                        .addGap(18, 18, 18)
                        .addComponent(emprestimosjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numTotaljLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(250, 250, 250)))
                .addComponent(dadosUserjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(499, 499, 499)
                .addComponent(nomeCollectionjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(superHeroisFundo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sycjLabel)
                        .addComponent(comicsjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(collectionsjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(emprestimosjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dadosUserjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(nomeCollectionjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numTotaljLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numTotaljTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(titulojTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editorajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numAtualjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numAtualjTextField)
                    .addComponent(editorajTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addGap(132, 132, 132)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancelarjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(salvarjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(superHeroisFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sycjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sycjLabelMouseClicked
        // TODO add your handling code here:
        TelaMenuPrincipal menu = new TelaMenuPrincipal();
        dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_sycjLabelMouseClicked

    private void comicsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comicsjButtonActionPerformed
        // TODO add your handling code here:
        TelaComics form = new TelaComics();
        dispose();
        form.setVisible(true);
    }//GEN-LAST:event_comicsjButtonActionPerformed

    private void collectionsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectionsjButtonActionPerformed
        // TODO add your handling code here:
        TelaCollections form = new TelaCollections();
        dispose();
        form.setVisible(true);
    }//GEN-LAST:event_collectionsjButtonActionPerformed

    private void emprestimosjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestimosjButtonActionPerformed
        // TODO add your handling code here:
        TelaLoans form = new TelaLoans();
        dispose();
        form.setVisible(true);
    }//GEN-LAST:event_emprestimosjButtonActionPerformed

    private void dadosUserjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dadosUserjButtonActionPerformed
        // TODO add your handling code here:
        TelaDadosUser form = new TelaDadosUser();
        dispose();
        form.setVisible(true);
    }//GEN-LAST:event_dadosUserjButtonActionPerformed

    private void editorajTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editorajTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editorajTextFieldActionPerformed

    private void cancelarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarjButtonActionPerformed
        // TODO add your handling code here:
        titulojTextField.setText("");
        numTotaljTextField.setText("");
        editorajTextField.setText("");
        numAtualjTextField.setText("");
        dispose();
        collections.setVisible(true);
    }//GEN-LAST:event_cancelarjButtonActionPerformed

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
        // TODO add your handling code here:
        CollectionDAO collectionDao = new CollectionDAO(login.getDataSource());
        if (!titulojTextField.getText().equals("")){
            collectionDao.adicionarDados(login.getId_user(), titulojTextField.getText(), editorajTextField.getText(), Integer.parseInt(numTotaljTextField.getText()), Integer.parseInt(numAtualjTextField.getText()));
            collections.modelo.clear();
            collections.getLista().clear();
            collections.povoarLista();
            dispose();
            collections.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Atualizacao nao realizada");
        }
    }//GEN-LAST:event_salvarjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAddCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAddCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAddCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAddCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAddCollection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarjButton;
    private javax.swing.JButton collectionsjButton;
    private javax.swing.JButton comicsjButton;
    private javax.swing.JButton dadosUserjButton;
    private javax.swing.JLabel editorajLabel;
    private javax.swing.JTextField editorajTextField;
    private javax.swing.JButton emprestimosjButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nomeCollectionjLabel;
    private javax.swing.JLabel numAtualjLabel;
    private javax.swing.JTextField numAtualjTextField;
    private javax.swing.JLabel numTotaljLabel;
    private javax.swing.JTextField numTotaljTextField;
    private javax.swing.JButton salvarjButton;
    private javax.swing.JLabel superHeroisFundo;
    private javax.swing.JLabel sycjLabel;
    private javax.swing.JLabel titulojLabel;
    private javax.swing.JTextField titulojTextField;
    // End of variables declaration//GEN-END:variables


}
