/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Mayara Medeiros
 */
public class TelaMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenuPrincipal
     */
    
    private static String nomeUser;
    
    public TelaMenuPrincipal() {
        initComponents();
        setNomeUser(nomeUser);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sycjLabel = new javax.swing.JLabel();
        superHeroisFundo = new javax.swing.JLabel();
        bemVindojPanel = new javax.swing.JPanel();
        bemVindojLabel = new javax.swing.JLabel();
        nomeUserjLabel = new javax.swing.JLabel();
        comicsjButton = new javax.swing.JButton();
        collectionsjButton = new javax.swing.JButton();
        emprestimosjButton = new javax.swing.JButton();
        dadosUserjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setLocation(new java.awt.Point(300, 100));
        setResizable(false);

        sycjLabel.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        sycjLabel.setForeground(new java.awt.Color(255, 255, 255));
        sycjLabel.setText("SeeYoursComics");

        superHeroisFundo.setBackground(new java.awt.Color(0, 0, 0));
        superHeroisFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/top-10-melhores-super-herois-noticias-the-history-channel (1).jpg"))); // NOI18N

        bemVindojPanel.setOpaque(false);

        bemVindojLabel.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        bemVindojLabel.setForeground(new java.awt.Color(255, 255, 255));
        bemVindojLabel.setText("Bem-Vindo(a)");

        nomeUserjLabel.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        nomeUserjLabel.setForeground(new java.awt.Color(255, 255, 255));
        nomeUserjLabel.setText("jLabel2");

        javax.swing.GroupLayout bemVindojPanelLayout = new javax.swing.GroupLayout(bemVindojPanel);
        bemVindojPanel.setLayout(bemVindojPanelLayout);
        bemVindojPanelLayout.setHorizontalGroup(
            bemVindojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bemVindojPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(bemVindojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeUserjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bemVindojPanelLayout.setVerticalGroup(
            bemVindojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bemVindojPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(bemVindojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bemVindojLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomeUserjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        comicsjButton.setBackground(new java.awt.Color(255, 255, 255));
        comicsjButton.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        comicsjButton.setText("Comics");
        comicsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comicsjButtonActionPerformed(evt);
            }
        });

        collectionsjButton.setBackground(new java.awt.Color(255, 255, 255));
        collectionsjButton.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        collectionsjButton.setText("Collections");
        collectionsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectionsjButtonActionPerformed(evt);
            }
        });

        emprestimosjButton.setBackground(new java.awt.Color(255, 255, 255));
        emprestimosjButton.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        emprestimosjButton.setText("Loans");
        emprestimosjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprestimosjButtonActionPerformed(evt);
            }
        });

        dadosUserjButton.setBackground(new java.awt.Color(255, 255, 255));
        dadosUserjButton.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        dadosUserjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user.png"))); // NOI18N
        dadosUserjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dadosUserjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(sycjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(comicsjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(collectionsjButton)
                .addGap(18, 18, 18)
                .addComponent(emprestimosjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dadosUserjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(bemVindojPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(superHeroisFundo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sycjLabel)
                        .addComponent(comicsjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(collectionsjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(emprestimosjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dadosUserjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(bemVindojPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(311, 311, 311))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(superHeroisFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comicsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comicsjButtonActionPerformed
        // TODO add your handling code here:
        TelaComics form = new TelaComics();
        dispose();
        form.setVisible(true);
        System.out.println("desgraca");
    }//GEN-LAST:event_comicsjButtonActionPerformed

    private void collectionsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectionsjButtonActionPerformed
        // TODO add your handling code here:
        TelaCollections form = new TelaCollections();
        dispose();
        form.setVisible(true);
    }//GEN-LAST:event_collectionsjButtonActionPerformed

    private void emprestimosjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestimosjButtonActionPerformed
        // TODO add your handling code here:
        TelaLoans form = new TelaLoans();
        dispose();
        form.setVisible(true);        
    }//GEN-LAST:event_emprestimosjButtonActionPerformed

    private void dadosUserjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dadosUserjButtonActionPerformed
        // TODO add your handling code here:
        TelaDadosUser form = new TelaDadosUser();
        dispose();
        form.setVisible(true);
    }//GEN-LAST:event_dadosUserjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bemVindojLabel;
    private javax.swing.JPanel bemVindojPanel;
    private javax.swing.JButton collectionsjButton;
    private javax.swing.JButton comicsjButton;
    private javax.swing.JButton dadosUserjButton;
    private javax.swing.JButton emprestimosjButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nomeUserjLabel;
    private javax.swing.JLabel superHeroisFundo;
    private javax.swing.JLabel sycjLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the nomeUser
     */
    public String getNomeUser() {
        return nomeUser;
    }

    /**
     * @param nomeUser the nomeUser to set
     */
    public void setNomeUser(String nomeUser) {
        this.nomeUser = nomeUser;
        nomeUserjLabel.setText(nomeUser);
    }
}
